Updated script export_reports to take in args.

diff --git a/scripts/export_reports b/scripts/export_reports
--- a/scripts/export_reports
+++ b/scripts/export_reports
@@ -4,10 +4,17 @@
 # contents of couchdb_views/qa_reports.js exists in the CouchDB database.
 # Upload the compressed directory to https://drive.google.com/#folders/0B0qFRp7UGda6U1NoZE9tTTJmZ1U
 
-username="couchadmin"
-password="couchM3"
-provider="scdl"
-port=5978
+die () {
+    echo >&2 "$@"
+    exit 1
+}
+
+[ $# -eq 4 ] || die "Usage ./export_reports username password provider port"
+
+username=$1
+password=$2
+provider=$3
+port=$4
 
 report[0]="type"
 report[1]="title"
@@ -25,13 +32,16 @@ report[12]="spatial_state"
 report[13]="data_provider"
 
 dir="${provider}_exports"
-rm -r $dir
+rm -r $dir "${dir}.zip"
 mkdir $dir
 
 for i in "${report[@]}"
 do
-       curl -o $dir/$i "http://$username:$password@camp.dpla.berkman.temphost.net:$port/dpla/_design/lists/_list/csv/$i"
-       curl -o "${dir}/${i}_count" "http://$username:$password@camp.dpla.berkman.temphost.net:$port/dpla/_design/lists/_list/count_csv/${i}_count?group=true"
+    echo "http://$username:$password@camp.dpla.berkman.temphost.net:$port/dpla/_design/lists/_list/csv/$i"
+    curl -o $dir/$i "http://$username:$password@camp.dpla.berkman.temphost.net:$port/dpla/_design/lists/_list/csv/$i"
+    curl -o "${dir}/${i}_count" "http://$username:$password@camp.dpla.berkman.temphost.net:$port/dpla/_design/lists/_list/count_csv/${i}_count?group=true"
 done
+
+[ $(ls $dir | wc -l) -ne 0 ] || die "Error: check parameters - username=$1 password=$2 provider=$3 port=$4"
 
 zip -r "${dir}.zip" $dir
